##    Copyright (c) 2025 Rich Bell <bellrichm@gmail.com>
##    See the file LICENSE.txt for your rights.

<div class="modal" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="alertModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header" id="alertModalHeader">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="alertModalBody">
                <div id="alertDetailModal" class="text-center"></div>
            </div>
            <div class="modal-footer" id="alertModalFooter"></div>
        </div>
    </div>
</div>