##    Copyright (c) 2021-2022 Rich Bell <bellrichm@gmail.com>
##    See the file LICENSE.txt for your rights.
<div class="row mb-4 justify-content-center">
<div class="col text-center">
    <a text_label="zoomControl_label"></a>
    <input type="text" id="datetimerange-input2" style="text-align:center">   
    <button id="resetRange" text_label="resetRange_label" onclick="resetRange()"></button>
</div>
</div>