##    Copyright (c) 2021-2022 Rich Bell <bellrichm@gmail.com>
##    See the file LICENSE.txt for your rights.

<nav class="navbar navbar-expand-md navbar-light bg-light justify-content-center">
    <div class="navbar-text">
        $gettext('zoomControl_label')
        <input type="text" id="datetimerange-input2" style="text-align:center">   
        <button id="resetRange" text_label="resetRange_label" onclick="resetRange()"></button>
    </div>
</nav>
